// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.

//here are three possible solutions the last two have O(n) time O(1) space
const findTheDifference = function (s, t) {
  const hash = {};
  for (let c of s) {
    hash[c] = hash[c] ? ++hash[c] : 1;
  }

  for (let c of t) {
    if (!hash[c]) return c;
    else --hash[c];
  }
};

const findTheDifference2 = function (s, t) {
  let diff = 0;
  for (let c of s) {
    diff += c.charCodeAt();
  }

  for (let c of t) {
    diff -= c.charCodeAt();
  }
  return String.fromCharCode(diff);
};

const findTheDifference3 = function (s, t) {
  let diff = 0;
  for (let c of t + s) {
    diff ^= c.charCodeAt();
  }
  return String.fromCharCode(diff);
};
